#ifndef MODELS_IDENTIFIERS_H
#define MODELS_IDENTIFIERS_H
/**
 * @file identifiers.h
 *
 * Define identifiers for states and signal events of the UML model.
 *
 * This file is automatically generated by the uml-serializer-c tool.
 * Do not modify manually.
 *
 * @author Matthias Brun (matthias.brun@eseo.fr)
 * @author Valentin Besnard (valentin.besnard@eseo.fr)
 */

#include "types_calibration.h"
#include "interpreter/active_object.h"
#include "interpreter/passive_object.h"

// Serialize root access to composite structure classes
#define ROOT_instMain 	passiveObjects.instMain
#ifdef WITH_OBSERVERS
#endif /* WITH_OBSERVERS */




#define STATE_Controller_Initial			0
#define STATE_Controller_Idle			1
#define STATE_Controller_RedOn			2




#define STATE_SimulatedLight_Initial			0
#define STATE_SimulatedLight_Off			1
#define STATE_SimulatedLight_On			2

#define STATE_SimulatedButton_Initial			0
#define STATE_SimulatedButton_Released			1
#define STATE_SimulatedButton_Pressed			2







#define SIGNAL_lightOn			(globalSignalEvents.lightOn)
#define SIGNAL_lightOff			(globalSignalEvents.lightOff)
#define SIGNAL_buttonPressed			(globalSignalEvents.buttonPressed)
#define SIGNAL_buttonReleased			(globalSignalEvents.buttonReleased)

#endif /* MODELS_IDENTIFIERS_H */
