#ifndef MODELS_IDENTIFIERS_H
#define MODELS_IDENTIFIERS_H
/**
 * @file identifiers.h
 *
 * Define identifiers for states and signal events of the UML model.
 *
 * This file is automatically generated by the uml-serializer-c tool.
 * Do not modify manually.
 *
 * @author Matthias Brun (matthias.brun@eseo.fr)
 * @author Valentin Besnard (valentin.besnard@eseo.fr)
 */

#include "types_calibration.h"
#include "interpreter/active_object.h"
#include "interpreter/passive_object.h"

// Serialize root access to composite structure classes
#define ROOT_instMain 	passiveObjects.instMain
#ifdef WITH_OBSERVERS
#endif /* WITH_OBSERVERS */





#define STATE_EntranceTC_Initial			0
#define STATE_EntranceTC_Detection			1

#define STATE_ExitTC_Initial			0
#define STATE_ExitTC_Detection			1

#define STATE_Controller_Initial			0
#define STATE_Controller_Idle			1
#define STATE_Controller_WaitRoadSignOn			2
#define STATE_Controller_FarDetection			3
#define STATE_Controller_CloseDetection			4
#define STATE_Controller_WaitRailwaySignOn			5
#define STATE_Controller_WaitGateOpen			6
#define STATE_Controller_WaitRoadSignOff			7

#define STATE_RoadSign_Initial			0
#define STATE_RoadSign_Inactive			1
#define STATE_RoadSign_Active			2

#define STATE_Gate_Initial			0
#define STATE_Gate_Open			1
#define STATE_Gate_Closed			2

#define STATE_RailwaySign_Initial			0
#define STATE_RailwaySign_Active			1
#define STATE_RailwaySign_Inactive			2






#define STATE_Train_Initial			0
#define STATE_Train_Idle			1
#define STATE_Train_Far			2
#define STATE_Train_Close			3
#define STATE_Train_Passing			4





#define SIGNAL_entranceDetection			(globalSignalEvents.entranceDetection)
#define SIGNAL_exitDetection			(globalSignalEvents.exitDetection)
#define SIGNAL_switchOn			(globalSignalEvents.switchOn)
#define SIGNAL_switchOff			(globalSignalEvents.switchOff)
#define SIGNAL_roadSignOn			(globalSignalEvents.roadSignOn)
#define SIGNAL_roadSignOff			(globalSignalEvents.roadSignOff)
#define SIGNAL_open			(globalSignalEvents.open)
#define SIGNAL_close			(globalSignalEvents.close)
#define SIGNAL_gateOpen			(globalSignalEvents.gateOpen)
#define SIGNAL_gateClosed			(globalSignalEvents.gateClosed)
#define SIGNAL_railwaySignOn			(globalSignalEvents.railwaySignOn)
#define SIGNAL_activation			(globalSignalEvents.activation)
#define SIGNAL_authorization			(globalSignalEvents.authorization)

#endif /* MODELS_IDENTIFIERS_H */
