#ifndef MODEL_H
#define MODEL_H
/**
 * @file model.h
 *
 * Define the UML model to interpret.
 *
 * This file is automatically generated by the uml-serializer-c tool.
 * Do not modify manually.
 *
 * @author Matthias Brun (matthias.brun@eseo.fr)
 * @author Valentin Besnard (valentin.besnard@eseo.fr)
 */

#include "types_calibration.h"
//#include "interpreter/interpreter.h"
#include "interpreter/active_object.h"
#include "interpreter/passive_object.h"

/**
 * Number of observers in the model (observers that are active objects).
 */
#define NB_OBSERVERS (0)

/**
 * Typedef for events parameters.
 */
typedef struct entranceDetection_signal_parameters entranceDetection_signal_parameters;
typedef struct exitDetection_signal_parameters exitDetection_signal_parameters;
typedef struct switchOn_signal_parameters switchOn_signal_parameters;
typedef struct switchOff_signal_parameters switchOff_signal_parameters;
typedef struct roadSignOn_signal_parameters roadSignOn_signal_parameters;
typedef struct roadSignOff_signal_parameters roadSignOff_signal_parameters;
typedef struct open_signal_parameters open_signal_parameters;
typedef struct close_signal_parameters close_signal_parameters;
typedef struct gateOpen_signal_parameters gateOpen_signal_parameters;
typedef struct gateClosed_signal_parameters gateClosed_signal_parameters;
typedef struct railwaySignOn_signal_parameters railwaySignOn_signal_parameters;
typedef struct activation_signal_parameters activation_signal_parameters;
typedef struct authorization_signal_parameters authorization_signal_parameters;

/**
 * Typedef for events.
 */
typedef struct EntranceTC_events EntranceTC_events;
typedef struct ExitTC_events ExitTC_events;
typedef struct Controller_events Controller_events;
#ifdef WITH_OBSERVERS
#endif /* WITH_OBSERVERS */

/**
 * Typedef of store types.
 */
typedef struct System_store System_store;
typedef struct System_od  System_od;
typedef struct EntranceTCPort_store EntranceTCPort_store;
typedef struct EntranceTCPort_od  EntranceTCPort_od;
typedef struct ExitTCPort_store ExitTCPort_store;
typedef struct ExitTCPort_od  ExitTCPort_od;
typedef struct RailwaySignPort_store RailwaySignPort_store;
typedef struct RailwaySignPort_od  RailwaySignPort_od;
typedef struct EntranceTC_store EntranceTC_store;
typedef struct EntranceTC_ep_params EntranceTC_ep_params;
typedef struct EntranceTC_od  EntranceTC_od;
typedef struct ExitTC_store ExitTC_store;
typedef struct ExitTC_ep_params ExitTC_ep_params;
typedef struct ExitTC_od  ExitTC_od;
typedef struct Controller_store Controller_store;
typedef struct Controller_ep_params Controller_ep_params;
typedef struct Controller_od  Controller_od;
typedef struct RoadSign_store RoadSign_store;
typedef struct RoadSign_ep_params RoadSign_ep_params;
typedef struct RoadSign_od  RoadSign_od;
typedef struct Gate_store Gate_store;
typedef struct Gate_ep_params Gate_ep_params;
typedef struct Gate_od  Gate_od;
typedef struct RailwaySign_store RailwaySign_store;
typedef struct RailwaySign_ep_params RailwaySign_ep_params;
typedef struct RailwaySign_od  RailwaySign_od;
typedef struct Main_store Main_store;
typedef struct Main_od  Main_od;
typedef struct Environment_store Environment_store;
typedef struct Environment_od  Environment_od;
typedef struct EnvEntranceTCPort_store EnvEntranceTCPort_store;
typedef struct EnvEntranceTCPort_od  EnvEntranceTCPort_od;
typedef struct EnvExitTCPort_store EnvExitTCPort_store;
typedef struct EnvExitTCPort_od  EnvExitTCPort_od;
typedef struct EnvRailwaySignPort_store EnvRailwaySignPort_store;
typedef struct EnvRailwaySignPort_od  EnvRailwaySignPort_od;
typedef struct Train_store Train_store;
typedef struct Train_ep_params Train_ep_params;
typedef struct Train_od  Train_od;
typedef struct ActivationProvider_store ActivationProvider_store;
typedef struct ActivationProvider_od  ActivationProvider_od;
typedef struct ActivationUser_store ActivationUser_store;
typedef struct ActivationUser_od  ActivationUser_od;
typedef struct AuthorizationProvider_store AuthorizationProvider_store;
typedef struct AuthorizationProvider_od  AuthorizationProvider_od;
typedef struct AuthorizationUser_store AuthorizationUser_store;
typedef struct AuthorizationUser_od  AuthorizationUser_od;
/**
 * Typedef of the Store type.
 */
typedef struct Store Store;

/**
 * Typedef for signal events.
 */
typedef struct SignalEvents SignalEvents;


/**
 * Typedef of read-only properties types for classes.
 */
typedef struct ActivationProvider_properties_ro ActivationProvider_properties_ro;
typedef struct Environment_properties_ro Environment_properties_ro;
typedef struct EnvExitTCPort_properties_ro EnvExitTCPort_properties_ro;
typedef struct EntranceTCPort_properties_ro EntranceTCPort_properties_ro;
typedef struct Controller_properties_ro Controller_properties_ro;
typedef struct RailwaySign_properties_ro RailwaySign_properties_ro;
typedef struct Train_properties_ro Train_properties_ro;
typedef struct AuthorizationUser_properties_ro AuthorizationUser_properties_ro;
typedef struct Main_properties_ro Main_properties_ro;
typedef struct RoadSign_properties_ro RoadSign_properties_ro;
typedef struct ExitTC_properties_ro ExitTC_properties_ro;
typedef struct System_properties_ro System_properties_ro;
typedef struct ExitTCPort_properties_ro ExitTCPort_properties_ro;
typedef struct EnvEntranceTCPort_properties_ro EnvEntranceTCPort_properties_ro;
typedef struct RailwaySignPort_properties_ro RailwaySignPort_properties_ro;
typedef struct Gate_properties_ro Gate_properties_ro;
typedef struct ActivationUser_properties_ro ActivationUser_properties_ro;
typedef struct EnvRailwaySignPort_properties_ro EnvRailwaySignPort_properties_ro;
typedef struct AuthorizationProvider_properties_ro AuthorizationProvider_properties_ro;
typedef struct EntranceTC_properties_ro EntranceTC_properties_ro;
typedef struct PropertiesRO PropertiesRO;

/**
 * The number of fireable transitions of the system.
 */
#define MAX_FIREABLE_SYSTEM  (11)

/**
 * Typedef for mutability of properties.
 */
typedef struct System_mutability System_mutability;
typedef struct EntranceTCPort_mutability EntranceTCPort_mutability;
typedef struct ExitTCPort_mutability ExitTCPort_mutability;
typedef struct RailwaySignPort_mutability RailwaySignPort_mutability;
typedef struct EntranceTC_mutability EntranceTC_mutability;
typedef struct ExitTC_mutability ExitTC_mutability;
typedef struct Controller_mutability Controller_mutability;
typedef struct RoadSign_mutability RoadSign_mutability;
typedef struct Gate_mutability Gate_mutability;
typedef struct RailwaySign_mutability RailwaySign_mutability;
typedef struct Main_mutability Main_mutability;
typedef struct Environment_mutability Environment_mutability;
typedef struct EnvEntranceTCPort_mutability EnvEntranceTCPort_mutability;
typedef struct EnvExitTCPort_mutability EnvExitTCPort_mutability;
typedef struct EnvRailwaySignPort_mutability EnvRailwaySignPort_mutability;
typedef struct Train_mutability Train_mutability;
typedef struct ActivationProvider_mutability ActivationProvider_mutability;
typedef struct ActivationUser_mutability ActivationUser_mutability;
typedef struct AuthorizationProvider_mutability AuthorizationProvider_mutability;
typedef struct AuthorizationUser_mutability AuthorizationUser_mutability;

/**
 * Typedef for properties types.
 */
typedef struct System_PropertiesTypes System_PropertiesTypes;
typedef struct EntranceTCPort_PropertiesTypes EntranceTCPort_PropertiesTypes;
typedef struct ExitTCPort_PropertiesTypes ExitTCPort_PropertiesTypes;
typedef struct RailwaySignPort_PropertiesTypes RailwaySignPort_PropertiesTypes;
typedef struct EntranceTC_PropertiesTypes EntranceTC_PropertiesTypes;
typedef struct ExitTC_PropertiesTypes ExitTC_PropertiesTypes;
typedef struct Controller_PropertiesTypes Controller_PropertiesTypes;
typedef struct RoadSign_PropertiesTypes RoadSign_PropertiesTypes;
typedef struct Gate_PropertiesTypes Gate_PropertiesTypes;
typedef struct RailwaySign_PropertiesTypes RailwaySign_PropertiesTypes;
typedef struct Main_PropertiesTypes Main_PropertiesTypes;
typedef struct Environment_PropertiesTypes Environment_PropertiesTypes;
typedef struct EnvEntranceTCPort_PropertiesTypes EnvEntranceTCPort_PropertiesTypes;
typedef struct EnvExitTCPort_PropertiesTypes EnvExitTCPort_PropertiesTypes;
typedef struct EnvRailwaySignPort_PropertiesTypes EnvRailwaySignPort_PropertiesTypes;
typedef struct Train_PropertiesTypes Train_PropertiesTypes;
typedef struct ActivationProvider_PropertiesTypes ActivationProvider_PropertiesTypes;
typedef struct ActivationUser_PropertiesTypes ActivationUser_PropertiesTypes;
typedef struct AuthorizationProvider_PropertiesTypes AuthorizationProvider_PropertiesTypes;
typedef struct AuthorizationUser_PropertiesTypes AuthorizationUser_PropertiesTypes;

/**
 * Typedef for class information.
 */
typedef struct System_classInfo System_classInfo;
typedef struct EntranceTCPort_classInfo EntranceTCPort_classInfo;
typedef struct ExitTCPort_classInfo ExitTCPort_classInfo;
typedef struct RailwaySignPort_classInfo RailwaySignPort_classInfo;
typedef struct EntranceTC_classInfo EntranceTC_classInfo;
typedef struct ExitTC_classInfo ExitTC_classInfo;
typedef struct Controller_classInfo Controller_classInfo;
typedef struct RoadSign_classInfo RoadSign_classInfo;
typedef struct Gate_classInfo Gate_classInfo;
typedef struct RailwaySign_classInfo RailwaySign_classInfo;
typedef struct Main_classInfo Main_classInfo;
typedef struct Environment_classInfo Environment_classInfo;
typedef struct EnvEntranceTCPort_classInfo EnvEntranceTCPort_classInfo;
typedef struct EnvExitTCPort_classInfo EnvExitTCPort_classInfo;
typedef struct EnvRailwaySignPort_classInfo EnvRailwaySignPort_classInfo;
typedef struct Train_classInfo Train_classInfo;
typedef struct ActivationProvider_classInfo ActivationProvider_classInfo;
typedef struct ActivationUser_classInfo ActivationUser_classInfo;
typedef struct AuthorizationProvider_classInfo AuthorizationProvider_classInfo;
typedef struct AuthorizationUser_classInfo AuthorizationUser_classInfo;

/**
 * Typedef of active objects types.
 */
SPECIFIC_TYPEDEF_Object(EntranceTC)
SPECIFIC_TYPEDEF_Object(ExitTC)
SPECIFIC_TYPEDEF_Object(Controller)
SPECIFIC_TYPEDEF_Object(RoadSign)
SPECIFIC_TYPEDEF_Object(Gate)
SPECIFIC_TYPEDEF_Object(RailwaySign)
SPECIFIC_TYPEDEF_Object(Train)
typedef struct ActiveObjects ActiveObjects;

/**
 * Typedef of passive objects types.
 */
SPECIFIC_TYPEDEF_Object(System)
SPECIFIC_TYPEDEF_Object(EntranceTCPort)
SPECIFIC_TYPEDEF_Object(ExitTCPort)
SPECIFIC_TYPEDEF_Object(RailwaySignPort)
SPECIFIC_TYPEDEF_Object(Main)
SPECIFIC_TYPEDEF_Object(Environment)
SPECIFIC_TYPEDEF_Object(EnvEntranceTCPort)
SPECIFIC_TYPEDEF_Object(EnvExitTCPort)
SPECIFIC_TYPEDEF_Object(EnvRailwaySignPort)
SPECIFIC_TYPEDEF_Object(ActivationProvider)
SPECIFIC_TYPEDEF_Object(ActivationUser)
SPECIFIC_TYPEDEF_Object(AuthorizationProvider)
SPECIFIC_TYPEDEF_Object(AuthorizationUser)
typedef struct PassiveObjects PassiveObjects;

/**
 * Typedef for operations type.
 */
typedef struct Environment_operations Environment_operations;
typedef void (*Environment_method)(Environment_Object * this, void * __unused_params);

typedef struct ActivationProvider_operations ActivationProvider_operations;
typedef void (*ActivationProvider_method)(ActivationProvider_Object * this, void * __unused_params);

typedef struct EnvExitTCPort_operations EnvExitTCPort_operations;
typedef void (*EnvExitTCPort_method)(EnvExitTCPort_Object * this, void * __unused_params);

typedef struct EntranceTCPort_operations EntranceTCPort_operations;
typedef void (*EntranceTCPort_method)(EntranceTCPort_Object * this, void * __unused_params);

typedef struct Controller_operations Controller_operations;
typedef void (*Controller_method)(Controller_Object * this, void * __unused_params);

typedef struct RailwaySign_operations RailwaySign_operations;
typedef void (*RailwaySign_method)(RailwaySign_Object * this, void * __unused_params);

typedef struct Train_operations Train_operations;
typedef void (*Train_method)(Train_Object * this, void * __unused_params);

typedef struct AuthorizationUser_operations AuthorizationUser_operations;
typedef void (*AuthorizationUser_method)(AuthorizationUser_Object * this, void * __unused_params);

typedef struct Main_operations Main_operations;
typedef void (*Main_method)(Main_Object * this, void * __unused_params);

typedef struct RoadSign_operations RoadSign_operations;
typedef void (*RoadSign_method)(RoadSign_Object * this, void * __unused_params);

typedef struct ExitTC_operations ExitTC_operations;
typedef void (*ExitTC_method)(ExitTC_Object * this, void * __unused_params);

typedef struct System_operations System_operations;
typedef void (*System_method)(System_Object * this, void * __unused_params);

typedef struct ExitTCPort_operations ExitTCPort_operations;
typedef void (*ExitTCPort_method)(ExitTCPort_Object * this, void * __unused_params);

typedef struct EnvEntranceTCPort_operations EnvEntranceTCPort_operations;
typedef void (*EnvEntranceTCPort_method)(EnvEntranceTCPort_Object * this, void * __unused_params);

typedef struct RailwaySignPort_operations RailwaySignPort_operations;
typedef void (*RailwaySignPort_method)(RailwaySignPort_Object * this, void * __unused_params);

typedef struct Gate_operations Gate_operations;
typedef void (*Gate_method)(Gate_Object * this, void * __unused_params);

typedef struct ActivationUser_operations ActivationUser_operations;
typedef void (*ActivationUser_method)(ActivationUser_Object * this, void * __unused_params);

typedef struct EnvRailwaySignPort_operations EnvRailwaySignPort_operations;
typedef void (*EnvRailwaySignPort_method)(EnvRailwaySignPort_Object * this, void * __unused_params);

typedef struct EntranceTC_operations EntranceTC_operations;
typedef void (*EntranceTC_method)(EntranceTC_Object * this, void * __unused_params);

typedef struct AuthorizationProvider_operations AuthorizationProvider_operations;
typedef void (*AuthorizationProvider_method)(AuthorizationProvider_Object * this, void * __unused_params);

/**
 * Typedef for ports.
 */
typedef struct Ports Ports;




#define NB_MODEL_PARTS	(4)
extern C_UML_Model * model_to_interpret[NB_MODEL_PARTS];

/**
 * Declarations of types for events parameters.
 */
/**
 * Type entranceDetection_signal_parameters corresponding to parameters of the event entranceDetection.
 */
struct entranceDetection_signal_parameters {
	int32_t id;
};
/**
 * Type exitDetection_signal_parameters corresponding to parameters of the event exitDetection.
 */
struct exitDetection_signal_parameters {
	int32_t id;
};
/**
 * Type switchOn_signal_parameters corresponding to parameters of the event switchOn.
 */
struct switchOn_signal_parameters {
};
/**
 * Type switchOff_signal_parameters corresponding to parameters of the event switchOff.
 */
struct switchOff_signal_parameters {
};
/**
 * Type roadSignOn_signal_parameters corresponding to parameters of the event roadSignOn.
 */
struct roadSignOn_signal_parameters {
};
/**
 * Type roadSignOff_signal_parameters corresponding to parameters of the event roadSignOff.
 */
struct roadSignOff_signal_parameters {
};
/**
 * Type open_signal_parameters corresponding to parameters of the event open.
 */
struct open_signal_parameters {
};
/**
 * Type close_signal_parameters corresponding to parameters of the event close.
 */
struct close_signal_parameters {
};
/**
 * Type gateOpen_signal_parameters corresponding to parameters of the event gateOpen.
 */
struct gateOpen_signal_parameters {
};
/**
 * Type gateClosed_signal_parameters corresponding to parameters of the event gateClosed.
 */
struct gateClosed_signal_parameters {
};
/**
 * Type railwaySignOn_signal_parameters corresponding to parameters of the event railwaySignOn.
 */
struct railwaySignOn_signal_parameters {
};
/**
 * Type activation_signal_parameters corresponding to parameters of the event activation.
 */
struct activation_signal_parameters {
	int32_t id;
};
/**
 * Type authorization_signal_parameters corresponding to parameters of the event authorization.
 */
struct authorization_signal_parameters {
};

/**
 * Declarations of types for events.
 */
/**
 * Type EntranceTC_events corresponding to an event of the event pool.
 */
struct EntranceTC_events {
	union {
		activation_signal_parameters activation_params;
	};
};
/**
 * Type ExitTC_events corresponding to an event of the event pool.
 */
struct ExitTC_events {
	union {
		activation_signal_parameters activation_params;
	};
};
/**
 * Type Controller_events corresponding to an event of the event pool.
 */
struct Controller_events {
	union {
		entranceDetection_signal_parameters entranceDetection_params;
		exitDetection_signal_parameters exitDetection_params;
	};
};
#ifdef WITH_OBSERVERS
#endif /* WITH_OBSERVERS */

/**
 * Declaration of store types.
 */
/**
 * The object data (e.g., attributes) type for the System class.
 */
struct System_od {
};
/**
 * The store type for the System class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct System_store {
};
/**
 * The object data (e.g., attributes) type for the EntranceTCPort class.
 */
struct EntranceTCPort_od {
};
/**
 * The store type for the EntranceTCPort class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct EntranceTCPort_store {
};
/**
 * The object data (e.g., attributes) type for the ExitTCPort class.
 */
struct ExitTCPort_od {
};
/**
 * The store type for the ExitTCPort class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct ExitTCPort_store {
};
/**
 * The object data (e.g., attributes) type for the RailwaySignPort class.
 */
struct RailwaySignPort_od {
};
/**
 * The store type for the RailwaySignPort class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct RailwaySignPort_store {
};
/**
 * The event pool parameters type for the EntranceTC class.
 */
struct EntranceTC_ep_params {
	EntranceTC_events eventOccurred[EVENT_POOL_SIZE];
};
/**
 * The object data (e.g., attributes) type for the EntranceTC class.
 */
struct EntranceTC_od {
	int32_t id;
};
/**
 * The store type for the EntranceTC class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct EntranceTC_store {
	uint32_t cs;
	EventPoolStore ep;
	EntranceTC_ep_params ep_params;
	EntranceTC_od od;
};
/**
 * The event pool parameters type for the ExitTC class.
 */
struct ExitTC_ep_params {
	ExitTC_events eventOccurred[EVENT_POOL_SIZE];
};
/**
 * The object data (e.g., attributes) type for the ExitTC class.
 */
struct ExitTC_od {
	int32_t id;
};
/**
 * The store type for the ExitTC class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct ExitTC_store {
	uint32_t cs;
	EventPoolStore ep;
	ExitTC_ep_params ep_params;
	ExitTC_od od;
};
/**
 * The event pool parameters type for the Controller class.
 */
struct Controller_ep_params {
	Controller_events eventOccurred[EVENT_POOL_SIZE];
};
/**
 * The object data (e.g., attributes) type for the Controller class.
 */
struct Controller_od {
	int32_t nbEngagedTrains;
};
/**
 * The store type for the Controller class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct Controller_store {
	uint32_t cs;
	EventPoolStore ep;
	Controller_ep_params ep_params;
	Controller_od od;
};
/**
 * The object data (e.g., attributes) type for the RoadSign class.
 */
struct RoadSign_od {
};
/**
 * The store type for the RoadSign class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct RoadSign_store {
	uint32_t cs;
	EventPoolStore ep;
};
/**
 * The object data (e.g., attributes) type for the Gate class.
 */
struct Gate_od {
};
/**
 * The store type for the Gate class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct Gate_store {
	uint32_t cs;
	EventPoolStore ep;
};
/**
 * The object data (e.g., attributes) type for the RailwaySign class.
 */
struct RailwaySign_od {
	int32_t id;
};
/**
 * The store type for the RailwaySign class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct RailwaySign_store {
	uint32_t cs;
	EventPoolStore ep;
	RailwaySign_od od;
};
/**
 * The object data (e.g., attributes) type for the Main class.
 */
struct Main_od {
};
/**
 * The store type for the Main class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct Main_store {
};
/**
 * The object data (e.g., attributes) type for the Environment class.
 */
struct Environment_od {
};
/**
 * The store type for the Environment class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct Environment_store {
};
/**
 * The object data (e.g., attributes) type for the EnvEntranceTCPort class.
 */
struct EnvEntranceTCPort_od {
};
/**
 * The store type for the EnvEntranceTCPort class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct EnvEntranceTCPort_store {
};
/**
 * The object data (e.g., attributes) type for the EnvExitTCPort class.
 */
struct EnvExitTCPort_od {
};
/**
 * The store type for the EnvExitTCPort class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct EnvExitTCPort_store {
};
/**
 * The object data (e.g., attributes) type for the EnvRailwaySignPort class.
 */
struct EnvRailwaySignPort_od {
};
/**
 * The store type for the EnvRailwaySignPort class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct EnvRailwaySignPort_store {
};
/**
 * The object data (e.g., attributes) type for the Train class.
 */
struct Train_od {
};
/**
 * The store type for the Train class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct Train_store {
	uint32_t cs;
	EventPoolStore ep;
};
/**
 * The object data (e.g., attributes) type for the ActivationProvider class.
 */
struct ActivationProvider_od {
};
/**
 * The store type for the ActivationProvider class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct ActivationProvider_store {
};
/**
 * The object data (e.g., attributes) type for the ActivationUser class.
 */
struct ActivationUser_od {
};
/**
 * The store type for the ActivationUser class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct ActivationUser_store {
};
/**
 * The object data (e.g., attributes) type for the AuthorizationProvider class.
 */
struct AuthorizationProvider_od {
};
/**
 * The store type for the AuthorizationProvider class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct AuthorizationProvider_store {
};
/**
 * The object data (e.g., attributes) type for the AuthorizationUser class.
 */
struct AuthorizationUser_od {
};
/**
 * The store type for the AuthorizationUser class. It contains:
 * 		 - value of its current state
 * 		 - content of its event pool
 * 		 - values of its attributes
 */
struct AuthorizationUser_store {
};
/**
 * The Store type used to gather dynamic data of each active object.
 */
struct Store {
	#ifdef WITH_SCHEDULING_STATE
	uint32_t scheduling_state;
	#endif /* WITH_SCHEDULING_STATE */
	Main_store instMain;
	Environment_store instMain_env;
	Train_store instMain_env_train;
	EnvEntranceTCPort_store instMain_env_tcEntrancePort0;
	EnvEntranceTCPort_store instMain_env_tcEntrancePort1;
	EnvExitTCPort_store instMain_env_tcExitPort;
	EnvRailwaySignPort_store instMain_env_railwaySignPort;
	System_store instMain_sys;
	EntranceTC_store instMain_sys_tcEntrance0;
	EntranceTC_store instMain_sys_tcEntrance1;
	ExitTC_store instMain_sys_tcExit;
	Controller_store instMain_sys_controller;
	RailwaySign_store instMain_sys_railwaySign;
	RoadSign_store instMain_sys_roadSign;
	Gate_store instMain_sys_gate;
	EntranceTCPort_store instMain_sys_tcEntrancePort0;
	EntranceTCPort_store instMain_sys_tcEntrancePort1;
	ExitTCPort_store instMain_sys_tcExitPort;
	RailwaySignPort_store instMain_sys_railwaySignPort;
	#ifdef WITH_OBSERVERS
	#endif /* WITH_OBSERVERS */
};
extern Store store;

#ifdef ANALYSIS_WITH_DIFF
extern Store refStore;
#endif /* ANALYSIS_WITH_DIFF */

/**
 * The SignalEvents type used to gather all signal events.
 */
struct SignalEvents {
	UML_SignalEvent * entranceDetection;
	UML_SignalEvent * exitDetection;
	UML_SignalEvent * switchOn;
	UML_SignalEvent * switchOff;
	UML_SignalEvent * roadSignOn;
	UML_SignalEvent * roadSignOff;
	UML_SignalEvent * open;
	UML_SignalEvent * close;
	UML_SignalEvent * gateOpen;
	UML_SignalEvent * gateClosed;
	UML_SignalEvent * railwaySignOn;
	UML_SignalEvent * activation;
	UML_SignalEvent * authorization;
};
extern SignalEvents globalSignalEvents;


/**
 * Structures initializer for operations.
 */
struct Environment_operations {
};

struct ActivationProvider_operations {
};

struct EnvExitTCPort_operations {
};

struct EntranceTCPort_operations {
};

struct Controller_operations {
};

struct RailwaySign_operations {
};

struct Train_operations {
};

struct AuthorizationUser_operations {
};

struct Main_operations {
};

struct RoadSign_operations {
};

struct ExitTC_operations {
};

struct System_operations {
};

struct ExitTCPort_operations {
};

struct EnvEntranceTCPort_operations {
};

struct RailwaySignPort_operations {
};

struct Gate_operations {
};

struct ActivationUser_operations {
};

struct EnvRailwaySignPort_operations {
};

struct EntranceTC_operations {
};

struct AuthorizationProvider_operations {
};


/**
 * Macros for the mutability field of mutability structure.
 */
#define ABSTRACT_MUTABILITY_System  bool tcEntrance_isMutable		:1;	\
	bool tcEntrancePort_isMutable		:1;	\
	bool railwaySignPort_isMutable		:1;	\
	bool gate_isMutable		:1;	\
	bool tcExitPort_isMutable		:1;	\
	bool controller_isMutable		:1;	\
	bool railwaySign_isMutable		:1;	\
	bool tcExit_isMutable		:1;	\
	bool roadSign_isMutable		:1;

#define ABSTRACT_MUTABILITY_EntranceTCPort  bool envTcEntrancePort_isMutable		:1;	\
	bool tcEntrance_isMutable		:1;

#define ABSTRACT_MUTABILITY_ExitTCPort  bool envTcExitPort_isMutable		:1;	\
	bool tcExit_isMutable		:1;

#define ABSTRACT_MUTABILITY_RailwaySignPort  bool railwaySign_isMutable		:1;	\
	bool envRailwaySignPort_isMutable		:1;

#define ABSTRACT_MUTABILITY_EntranceTC  bool controller_isMutable		:1;	\
	bool train_isMutable		:1;	\
	bool id_isMutable		:1;

#define ABSTRACT_MUTABILITY_ExitTC  bool tcExitPort_isMutable		:1;	\
	bool controller_isMutable		:1;	\
	bool id_isMutable		:1;

#define ABSTRACT_MUTABILITY_Controller  bool tcEntrance_isMutable		:1;	\
	bool tcExit_isMutable		:1;	\
	bool roadSign_isMutable		:1;	\
	bool railwaySign_isMutable		:1;	\
	bool gate_isMutable		:1;	\
	bool nbEngagedTrains_isMutable		:1;

#define ABSTRACT_MUTABILITY_RoadSign  bool controller_isMutable		:1;

#define ABSTRACT_MUTABILITY_Gate  bool controller_isMutable		:1;

#define ABSTRACT_MUTABILITY_RailwaySign  bool train_isMutable		:1;	\
	bool controller_isMutable		:1;	\
	bool id_isMutable		:1;

#define ABSTRACT_MUTABILITY_Main  bool env_isMutable		:1;	\
	bool sys_isMutable		:1;

#define ABSTRACT_MUTABILITY_Environment  bool railwaySignPort_isMutable		:1;	\
	bool tcExitPort_isMutable		:1;	\
	bool tcEntrancePort_isMutable		:1;	\
	bool train_isMutable		:1;

#define ABSTRACT_MUTABILITY_EnvEntranceTCPort  bool sysTcEntrancePort_isMutable		:1;	\
	bool train_isMutable		:1;

#define ABSTRACT_MUTABILITY_EnvExitTCPort  bool train_isMutable		:1;	\
	bool sysTcExitPort_isMutable		:1;

#define ABSTRACT_MUTABILITY_EnvRailwaySignPort  bool sysRailwaySignPort_isMutable		:1;	\
	bool train_isMutable		:1;

#define ABSTRACT_MUTABILITY_Train  bool tcExit_isMutable		:1;	\
	bool railwaySign_isMutable		:1;	\
	bool tcEntrance_isMutable		:1;

#define ABSTRACT_MUTABILITY_ActivationProvider  

#define ABSTRACT_MUTABILITY_ActivationUser  

#define ABSTRACT_MUTABILITY_AuthorizationProvider  

#define ABSTRACT_MUTABILITY_AuthorizationUser  

/**
 * Mutability structures.
 */
struct System_mutability {
	ABSTRACT_MUTABILITY_System
};

struct EntranceTCPort_mutability {
	ABSTRACT_MUTABILITY_ActivationProvider
	ABSTRACT_MUTABILITY_EntranceTCPort
};

struct ExitTCPort_mutability {
	ABSTRACT_MUTABILITY_ActivationProvider
	ABSTRACT_MUTABILITY_ExitTCPort
};

struct RailwaySignPort_mutability {
	ABSTRACT_MUTABILITY_AuthorizationUser
	ABSTRACT_MUTABILITY_RailwaySignPort
};

struct EntranceTC_mutability {
	ABSTRACT_MUTABILITY_ActivationProvider
	ABSTRACT_MUTABILITY_EntranceTC
};

struct ExitTC_mutability {
	ABSTRACT_MUTABILITY_ActivationProvider
	ABSTRACT_MUTABILITY_ExitTC
};

struct Controller_mutability {
	ABSTRACT_MUTABILITY_Controller
};

struct RoadSign_mutability {
	ABSTRACT_MUTABILITY_RoadSign
};

struct Gate_mutability {
	ABSTRACT_MUTABILITY_Gate
};

struct RailwaySign_mutability {
	ABSTRACT_MUTABILITY_AuthorizationUser
	ABSTRACT_MUTABILITY_RailwaySign
};

struct Main_mutability {
	ABSTRACT_MUTABILITY_Main
};

struct Environment_mutability {
	ABSTRACT_MUTABILITY_Environment
};

struct EnvEntranceTCPort_mutability {
	ABSTRACT_MUTABILITY_ActivationUser
	ABSTRACT_MUTABILITY_EnvEntranceTCPort
};

struct EnvExitTCPort_mutability {
	ABSTRACT_MUTABILITY_ActivationUser
	ABSTRACT_MUTABILITY_EnvExitTCPort
};

struct EnvRailwaySignPort_mutability {
	ABSTRACT_MUTABILITY_AuthorizationProvider
	ABSTRACT_MUTABILITY_EnvRailwaySignPort
};

struct Train_mutability {
	ABSTRACT_MUTABILITY_ActivationUser
	ABSTRACT_MUTABILITY_Train
};

struct ActivationProvider_mutability {
	ABSTRACT_MUTABILITY_ActivationProvider
};

struct ActivationUser_mutability {
	ABSTRACT_MUTABILITY_ActivationUser
};

struct AuthorizationProvider_mutability {
	ABSTRACT_MUTABILITY_AuthorizationProvider
};

struct AuthorizationUser_mutability {
	ABSTRACT_MUTABILITY_AuthorizationUser
};

/**
 * Macros for the properties_types field of properties type structure.
 */
#define ABSTRACT_PROPERTIES_TYPE_System  System_properties_ro * tcEntrance_type;	\
	System_properties_ro * tcEntrancePort_type;	\
	System_properties_ro * railwaySignPort_type;	\
	System_properties_ro * gate_type;	\
	System_properties_ro * tcExitPort_type;	\
	System_properties_ro * controller_type;	\
	System_properties_ro * railwaySign_type;	\
	System_properties_ro * tcExit_type;	\
	System_properties_ro * roadSign_type;

#define ABSTRACT_PROPERTIES_TYPE_EntranceTCPort  EntranceTCPort_properties_ro * envTcEntrancePort_type;	\
	EntranceTCPort_properties_ro * tcEntrance_type;

#define ABSTRACT_PROPERTIES_TYPE_ExitTCPort  ExitTCPort_properties_ro * envTcExitPort_type;	\
	ExitTCPort_properties_ro * tcExit_type;

#define ABSTRACT_PROPERTIES_TYPE_RailwaySignPort  RailwaySignPort_properties_ro * railwaySign_type;	\
	RailwaySignPort_properties_ro * envRailwaySignPort_type;

#define ABSTRACT_PROPERTIES_TYPE_EntranceTC  EntranceTC_properties_ro * controller_type;	\
	EntranceTC_properties_ro * train_type;	\
	EntranceTC_od * id_type;

#define ABSTRACT_PROPERTIES_TYPE_ExitTC  ExitTC_properties_ro * tcExitPort_type;	\
	ExitTC_properties_ro * controller_type;	\
	ExitTC_od * id_type;

#define ABSTRACT_PROPERTIES_TYPE_Controller  Controller_properties_ro * tcEntrance_type;	\
	Controller_properties_ro * tcExit_type;	\
	Controller_properties_ro * roadSign_type;	\
	Controller_properties_ro * railwaySign_type;	\
	Controller_properties_ro * gate_type;	\
	Controller_od * nbEngagedTrains_type;

#define ABSTRACT_PROPERTIES_TYPE_RoadSign  RoadSign_properties_ro * controller_type;

#define ABSTRACT_PROPERTIES_TYPE_Gate  Gate_properties_ro * controller_type;

#define ABSTRACT_PROPERTIES_TYPE_RailwaySign  RailwaySign_properties_ro * train_type;	\
	RailwaySign_properties_ro * controller_type;	\
	RailwaySign_od * id_type;

#define ABSTRACT_PROPERTIES_TYPE_Main  Main_properties_ro * env_type;	\
	Main_properties_ro * sys_type;

#define ABSTRACT_PROPERTIES_TYPE_Environment  Environment_properties_ro * railwaySignPort_type;	\
	Environment_properties_ro * tcExitPort_type;	\
	Environment_properties_ro * tcEntrancePort_type;	\
	Environment_properties_ro * train_type;

#define ABSTRACT_PROPERTIES_TYPE_EnvEntranceTCPort  EnvEntranceTCPort_properties_ro * sysTcEntrancePort_type;	\
	EnvEntranceTCPort_properties_ro * train_type;

#define ABSTRACT_PROPERTIES_TYPE_EnvExitTCPort  EnvExitTCPort_properties_ro * train_type;	\
	EnvExitTCPort_properties_ro * sysTcExitPort_type;

#define ABSTRACT_PROPERTIES_TYPE_EnvRailwaySignPort  EnvRailwaySignPort_properties_ro * sysRailwaySignPort_type;	\
	EnvRailwaySignPort_properties_ro * train_type;

#define ABSTRACT_PROPERTIES_TYPE_Train  Train_properties_ro * tcExit_type;	\
	Train_properties_ro * railwaySign_type;	\
	Train_properties_ro * tcEntrance_type;

#define ABSTRACT_PROPERTIES_TYPE_ActivationProvider  

#define ABSTRACT_PROPERTIES_TYPE_ActivationUser  

#define ABSTRACT_PROPERTIES_TYPE_AuthorizationProvider  

#define ABSTRACT_PROPERTIES_TYPE_AuthorizationUser  

/**
 * Properties type structures.
 */
struct System_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_System
};

struct EntranceTCPort_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationProvider
	ABSTRACT_PROPERTIES_TYPE_EntranceTCPort
};

struct ExitTCPort_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationProvider
	ABSTRACT_PROPERTIES_TYPE_ExitTCPort
};

struct RailwaySignPort_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_AuthorizationUser
	ABSTRACT_PROPERTIES_TYPE_RailwaySignPort
};

struct EntranceTC_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationProvider
	ABSTRACT_PROPERTIES_TYPE_EntranceTC
};

struct ExitTC_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationProvider
	ABSTRACT_PROPERTIES_TYPE_ExitTC
};

struct Controller_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_Controller
};

struct RoadSign_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_RoadSign
};

struct Gate_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_Gate
};

struct RailwaySign_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_AuthorizationUser
	ABSTRACT_PROPERTIES_TYPE_RailwaySign
};

struct Main_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_Main
};

struct Environment_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_Environment
};

struct EnvEntranceTCPort_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationUser
	ABSTRACT_PROPERTIES_TYPE_EnvEntranceTCPort
};

struct EnvExitTCPort_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationUser
	ABSTRACT_PROPERTIES_TYPE_EnvExitTCPort
};

struct EnvRailwaySignPort_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_AuthorizationProvider
	ABSTRACT_PROPERTIES_TYPE_EnvRailwaySignPort
};

struct Train_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationUser
	ABSTRACT_PROPERTIES_TYPE_Train
};

struct ActivationProvider_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationProvider
};

struct ActivationUser_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_ActivationUser
};

struct AuthorizationProvider_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_AuthorizationProvider
};

struct AuthorizationUser_PropertiesTypes {
	ABSTRACT_PROPERTIES_TYPE_AuthorizationUser
};


/**
 * Class information structures.
 */
struct System_classInfo {
	union {
		UML_Class * type;
		const System_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	System_mutability mutability;
};

struct EntranceTCPort_classInfo {
	union {
		UML_Class * type;
		const EntranceTCPort_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	EntranceTCPort_mutability mutability;
};

struct ExitTCPort_classInfo {
	union {
		UML_Class * type;
		const ExitTCPort_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	ExitTCPort_mutability mutability;
};

struct RailwaySignPort_classInfo {
	union {
		UML_Class * type;
		const RailwaySignPort_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	RailwaySignPort_mutability mutability;
};

struct EntranceTC_classInfo {
	union {
		UML_Class * type;
		const EntranceTC_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	EntranceTC_mutability mutability;
};

struct ExitTC_classInfo {
	union {
		UML_Class * type;
		const ExitTC_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	ExitTC_mutability mutability;
};

struct Controller_classInfo {
	union {
		UML_Class * type;
		const Controller_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	Controller_mutability mutability;
};

struct RoadSign_classInfo {
	union {
		UML_Class * type;
		const RoadSign_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	RoadSign_mutability mutability;
};

struct Gate_classInfo {
	union {
		UML_Class * type;
		const Gate_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	Gate_mutability mutability;
};

struct RailwaySign_classInfo {
	union {
		UML_Class * type;
		const RailwaySign_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	RailwaySign_mutability mutability;
};

struct Main_classInfo {
	union {
		UML_Class * type;
		const Main_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	Main_mutability mutability;
};

struct Environment_classInfo {
	union {
		UML_Class * type;
		const Environment_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	Environment_mutability mutability;
};

struct EnvEntranceTCPort_classInfo {
	union {
		UML_Class * type;
		const EnvEntranceTCPort_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	EnvEntranceTCPort_mutability mutability;
};

struct EnvExitTCPort_classInfo {
	union {
		UML_Class * type;
		const EnvExitTCPort_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	EnvExitTCPort_mutability mutability;
};

struct EnvRailwaySignPort_classInfo {
	union {
		UML_Class * type;
		const EnvRailwaySignPort_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	EnvRailwaySignPort_mutability mutability;
};

struct Train_classInfo {
	union {
		UML_Class * type;
		const Train_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	Train_mutability mutability;
};

struct ActivationProvider_classInfo {
	union {
		UML_Class * type;
		const ActivationProvider_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	ActivationProvider_mutability mutability;
};

struct ActivationUser_classInfo {
	union {
		UML_Class * type;
		const ActivationUser_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	ActivationUser_mutability mutability;
};

struct AuthorizationProvider_classInfo {
	union {
		UML_Class * type;
		const AuthorizationProvider_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	AuthorizationProvider_mutability mutability;
};

struct AuthorizationUser_classInfo {
	union {
		UML_Class * type;
		const AuthorizationUser_PropertiesTypes * properties_types; // Should not be dereferenced
	};
	AuthorizationUser_mutability mutability;
};

/**
 * Specific types for active objects.
 */
SPECIFIC_STRUCT_ActiveObject(EntranceTC)
SPECIFIC_STRUCT_ActiveObject(ExitTC)
SPECIFIC_STRUCT_ActiveObject(Controller)
SPECIFIC_STRUCT_ActiveObject(RoadSign)
SPECIFIC_STRUCT_ActiveObject(Gate)
SPECIFIC_STRUCT_ActiveObject(RailwaySign)
SPECIFIC_STRUCT_ActiveObject(Train)

/**
 * The ActiveObjects type used to gather all active objects
 */
struct ActiveObjects {
	Train_Object * instMain_env_train;
	EntranceTC_Object * instMain_sys_tcEntrance0;
	EntranceTC_Object * instMain_sys_tcEntrance1;
	ExitTC_Object * instMain_sys_tcExit;
	Controller_Object * instMain_sys_controller;
	RailwaySign_Object * instMain_sys_railwaySign;
	RoadSign_Object * instMain_sys_roadSign;
	Gate_Object * instMain_sys_gate;
	#ifdef WITH_OBSERVERS
	#endif /* WITH_OBSERVERS */
};
extern ActiveObjects activeObjects;

/**
 * Specific types for passive objects.
 */
SPECIFIC_STRUCT_PassiveObject(System)
SPECIFIC_STRUCT_PassiveObject(EntranceTCPort)
SPECIFIC_STRUCT_PassiveObject(ExitTCPort)
SPECIFIC_STRUCT_PassiveObject(RailwaySignPort)
SPECIFIC_STRUCT_PassiveObject(Main)
SPECIFIC_STRUCT_PassiveObject(Environment)
SPECIFIC_STRUCT_PassiveObject(EnvEntranceTCPort)
SPECIFIC_STRUCT_PassiveObject(EnvExitTCPort)
SPECIFIC_STRUCT_PassiveObject(EnvRailwaySignPort)
SPECIFIC_STRUCT_PassiveObject(ActivationProvider)
SPECIFIC_STRUCT_PassiveObject(ActivationUser)
SPECIFIC_STRUCT_PassiveObject(AuthorizationProvider)
SPECIFIC_STRUCT_PassiveObject(AuthorizationUser)

/**
 * The PassiveObjects type used to gather all passive objects
 */
struct PassiveObjects {
	Main_Object * instMain;
	Environment_Object * instMain_env;
	EnvEntranceTCPort_Object * instMain_env_tcEntrancePort0;
	EnvEntranceTCPort_Object * instMain_env_tcEntrancePort1;
	EnvExitTCPort_Object * instMain_env_tcExitPort;
	EnvRailwaySignPort_Object * instMain_env_railwaySignPort;
	System_Object * instMain_sys;
	EntranceTCPort_Object * instMain_sys_tcEntrancePort0;
	EntranceTCPort_Object * instMain_sys_tcEntrancePort1;
	ExitTCPort_Object * instMain_sys_tcExitPort;
	RailwaySignPort_Object * instMain_sys_railwaySignPort;
	#ifdef WITH_OBSERVERS
	#endif /* WITH_OBSERVERS */
};
extern PassiveObjects passiveObjects;

/**
 * Declaration of read-only properties types for superclasses.
 */
#define ABSTRACT_ACTIVATIONUSER_PROPERTIES_RO 
#define ABSTRACT_AUTHORIZATIONPROVIDER_PROPERTIES_RO 
#define ABSTRACT_ACTIVATIONPROVIDER_PROPERTIES_RO 
#define ABSTRACT_AUTHORIZATIONUSER_PROPERTIES_RO 
/**
 * Declaration of read-only properties types for classes.
 */
/**
 * The ActivationProvider_properties_ro type used to link instances of the ActivationProvider class with their properties.
 */
struct ActivationProvider_properties_ro {
};
/**
 * The Environment_properties_ro type used to link instances of the Environment class with their properties.
 */
struct Environment_properties_ro {
	EnvRailwaySignPort_Object * railwaySignPort;
	EnvExitTCPort_Object * tcExitPort;
	EnvEntranceTCPort_Object * tcEntrancePort[2];
	Train_Object * train;
};
/**
 * The EnvExitTCPort_properties_ro type used to link instances of the EnvExitTCPort class with their properties.
 */
struct EnvExitTCPort_properties_ro {
	ABSTRACT_ACTIVATIONUSER_PROPERTIES_RO
	Train_Object * train;
	ExitTCPort_Object * sysTcExitPort;
};
/**
 * The EntranceTCPort_properties_ro type used to link instances of the EntranceTCPort class with their properties.
 */
struct EntranceTCPort_properties_ro {
	ABSTRACT_ACTIVATIONPROVIDER_PROPERTIES_RO
	EnvEntranceTCPort_Object * envTcEntrancePort;
	EntranceTC_Object * tcEntrance;
};
/**
 * The Controller_properties_ro type used to link instances of the Controller class with their properties.
 */
struct Controller_properties_ro {
	EntranceTC_Object * tcEntrance[2];
	ExitTC_Object * tcExit;
	RoadSign_Object * roadSign;
	RailwaySign_Object * railwaySign;
	Gate_Object * gate;
};
/**
 * The RailwaySign_properties_ro type used to link instances of the RailwaySign class with their properties.
 */
struct RailwaySign_properties_ro {
	ABSTRACT_AUTHORIZATIONUSER_PROPERTIES_RO
	RailwaySignPort_Object * train;
	Controller_Object * controller;
};
/**
 * The Train_properties_ro type used to link instances of the Train class with their properties.
 */
struct Train_properties_ro {
	ABSTRACT_ACTIVATIONUSER_PROPERTIES_RO
	EnvExitTCPort_Object * tcExit;
	EnvRailwaySignPort_Object * railwaySign;
	EnvEntranceTCPort_Object * tcEntrance[2];
};
/**
 * The AuthorizationUser_properties_ro type used to link instances of the AuthorizationUser class with their properties.
 */
struct AuthorizationUser_properties_ro {
};
/**
 * The Main_properties_ro type used to link instances of the Main class with their properties.
 */
struct Main_properties_ro {
	Environment_Object * env;
	System_Object * sys;
};
/**
 * The RoadSign_properties_ro type used to link instances of the RoadSign class with their properties.
 */
struct RoadSign_properties_ro {
	Controller_Object * controller;
};
/**
 * The ExitTC_properties_ro type used to link instances of the ExitTC class with their properties.
 */
struct ExitTC_properties_ro {
	ABSTRACT_ACTIVATIONPROVIDER_PROPERTIES_RO
	ExitTCPort_Object * tcExitPort;
	Controller_Object * controller;
};
/**
 * The System_properties_ro type used to link instances of the System class with their properties.
 */
struct System_properties_ro {
	EntranceTC_Object * tcEntrance[2];
	EntranceTCPort_Object * tcEntrancePort[2];
	RailwaySignPort_Object * railwaySignPort;
	Gate_Object * gate;
	ExitTCPort_Object * tcExitPort;
	Controller_Object * controller;
	RailwaySign_Object * railwaySign;
	ExitTC_Object * tcExit;
	RoadSign_Object * roadSign;
};
/**
 * The ExitTCPort_properties_ro type used to link instances of the ExitTCPort class with their properties.
 */
struct ExitTCPort_properties_ro {
	ABSTRACT_ACTIVATIONPROVIDER_PROPERTIES_RO
	EnvExitTCPort_Object * envTcExitPort;
	ExitTC_Object * tcExit;
};
/**
 * The EnvEntranceTCPort_properties_ro type used to link instances of the EnvEntranceTCPort class with their properties.
 */
struct EnvEntranceTCPort_properties_ro {
	ABSTRACT_ACTIVATIONUSER_PROPERTIES_RO
	EntranceTCPort_Object * sysTcEntrancePort;
	Train_Object * train;
};
/**
 * The RailwaySignPort_properties_ro type used to link instances of the RailwaySignPort class with their properties.
 */
struct RailwaySignPort_properties_ro {
	ABSTRACT_AUTHORIZATIONUSER_PROPERTIES_RO
	RailwaySign_Object * railwaySign;
	EnvRailwaySignPort_Object * envRailwaySignPort;
};
/**
 * The Gate_properties_ro type used to link instances of the Gate class with their properties.
 */
struct Gate_properties_ro {
	Controller_Object * controller;
};
/**
 * The ActivationUser_properties_ro type used to link instances of the ActivationUser class with their properties.
 */
struct ActivationUser_properties_ro {
};
/**
 * The EnvRailwaySignPort_properties_ro type used to link instances of the EnvRailwaySignPort class with their properties.
 */
struct EnvRailwaySignPort_properties_ro {
	ABSTRACT_AUTHORIZATIONPROVIDER_PROPERTIES_RO
	RailwaySignPort_Object * sysRailwaySignPort;
	Train_Object * train;
};
/**
 * The AuthorizationProvider_properties_ro type used to link instances of the AuthorizationProvider class with their properties.
 */
struct AuthorizationProvider_properties_ro {
};
/**
 * The EntranceTC_properties_ro type used to link instances of the EntranceTC class with their properties.
 */
struct EntranceTC_properties_ro {
	ABSTRACT_ACTIVATIONPROVIDER_PROPERTIES_RO
	Controller_Object * controller;
	EntranceTCPort_Object * train;
};
/**
 * The global read-only properties type used to make links between objects.
 */
struct PropertiesRO {
	Main_properties_ro instMain;
	Environment_properties_ro instMain_env;
	Train_properties_ro instMain_env_train;
	EnvEntranceTCPort_properties_ro instMain_env_tcEntrancePort0;
	EnvEntranceTCPort_properties_ro instMain_env_tcEntrancePort1;
	EnvExitTCPort_properties_ro instMain_env_tcExitPort;
	EnvRailwaySignPort_properties_ro instMain_env_railwaySignPort;
	System_properties_ro instMain_sys;
	EntranceTC_properties_ro instMain_sys_tcEntrance0;
	EntranceTC_properties_ro instMain_sys_tcEntrance1;
	ExitTC_properties_ro instMain_sys_tcExit;
	Controller_properties_ro instMain_sys_controller;
	RailwaySign_properties_ro instMain_sys_railwaySign;
	RoadSign_properties_ro instMain_sys_roadSign;
	Gate_properties_ro instMain_sys_gate;
	EntranceTCPort_properties_ro instMain_sys_tcEntrancePort0;
	EntranceTCPort_properties_ro instMain_sys_tcEntrancePort1;
	ExitTCPort_properties_ro instMain_sys_tcExitPort;
	RailwaySignPort_properties_ro instMain_sys_railwaySignPort;
	#ifdef WITH_OBSERVERS
	#endif /* WITH_OBSERVERS */
};
extern PropertiesRO properties_ro;

/**
 * The Ports type used to gather all ports.
 */
struct Ports {
	UML_Port * LevelCrossingSystem__POINT__System__POINT__tcEntrancePort;
	UML_Port * LevelCrossingSystem__POINT__System__POINT__tcExitPort;
	UML_Port * LevelCrossingSystem__POINT__System__POINT__railwaySignPort;
	UML_Port * LevelCrossingEnvironment__POINT__Environment__POINT__tcEntrancePort;
	UML_Port * LevelCrossingEnvironment__POINT__Environment__POINT__tcExitPort;
	UML_Port * LevelCrossingEnvironment__POINT__Environment__POINT__railwaySignPort;
};
#ifdef EVENT_PORT_TAGGING
	extern Ports globalPorts;
#endif


#endif /* MODEL_H */
