

@startuml


	enum "UML_GpioPort" as Target_UML_GpioPort {
		UML_GPIO_PORT_A
		UML_GPIO_PORT_B
		UML_GPIO_PORT_C
		UML_GPIO_PORT_D
		UML_GPIO_PORT_E
		UML_GPIO_PORT_F
	}
	enum "UML_GpioPin" as Target_UML_GpioPin {
		UML_GPIO_PIN_0
		UML_GPIO_PIN_1
		UML_GPIO_PIN_2
		UML_GPIO_PIN_3
		UML_GPIO_PIN_4
		UML_GPIO_PIN_5
		UML_GPIO_PIN_6
		UML_GPIO_PIN_7
		UML_GPIO_PIN_8
		UML_GPIO_PIN_9
		UML_GPIO_PIN_10
		UML_GPIO_PIN_11
		UML_GPIO_PIN_12
		UML_GPIO_PIN_13
		UML_GPIO_PIN_14
		UML_GPIO_PIN_15
	}
	enum "UML_Timer" as Target_UML_Timer {
		UML_TIM_0
		UML_TIM_1
		UML_TIM_2
		UML_TIM_3
		UML_TIM_4
		UML_TIM_5
		UML_TIM_6
		UML_TIM_7
		UML_TIM_8
		UML_TIM_9
		UML_TIM_10
		UML_TIM_11
		UML_TIM_12
		UML_TIM_13
		UML_TIM_14
	}
	enum "UML_PwmChannel" as Target_UML_PwmChannel {
		UML_PWM_CH_0
		UML_PWM_CH_1
		UML_PWM_CH_2
		UML_PWM_CH_3
		UML_PWM_CH_4
	}
@enduml
